// Movies types
export const MOVIES_ERROR = 'MOVIES_ERROR';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SET_TERM_SUCCESS = 'SET_TERM_SUCCESS';
export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_NEXT_PAGE_START = 'FETCH_NEXT_PAGE_START';
export const FETCH_NEXT_PAGE_SUCCESS = 'FETCH_NEXT_PAGE_SUCCESS';
export const FETCH_PREVIOUS_PAGE_START = 'FETCH_PREVIOUS_PAGE_START';
export const FETCH_PREVIOUS_PAGE_SUCCESS = 'FETCH_PREVIOUS_PAGE_SUCCESS';
export const ADD_TO_NOMINATED_START = 'ADD_TO_NOMINATED_START';
export const ADD_TO_NOMINATED_SUCCESS = 'ADD_TO_NOMINATED_SUCCESS';
export const REMOVE_FROM_NOMINATED_START = 'REMOVE_FROM_NOMINATED_START';
export const REMOVE_FROM_NOMINATED_SUCCESS = 'REMOVE_FROM_NOMINATED_SUCCESS';
